version: '3'

services:
    auto_backup_db:
        image: auto_backup_db
        ports:
            - "7777:7000"
        volumes:
            - ./:/code
        environment:
            - ENV=pro
            - SQL_IP=203.154.135.217
            - SQL_USERNAME=root
            - SQL_PASSWORD=d]hk1234
            - SQL_DB=cozy
            - MONGO_IP=203.154.135.184
            - MONGO_USERNAME=mongo-onechatalpha-root2
            - MONGO_PASSWORD=9293709b13
        restart: always
        networks:
            - code-network
networks:
    code-network:
        driver: bridge
